// Downloads the webfonts and writes a self-hosted @font-face stylesheet.
//
// Fonts are self hosted rather than linked from Google so the site makes no
// third party requests, works offline, and needs no CSP allowance. Run once;
// the output is committed.
//
//   node tools/fetch-fonts.mjs

import fs from "node:fs";
import { createHash } from "node:crypto";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const OUT = path.join(ROOT, "public", "fonts");
const CSS = path.join(ROOT, "src", "styles", "fonts.css");

const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

// Lora for display: a warm humanist serif with entirely conventional
// letterforms. Fraunces was used first and rejected: its f carries a curled
// top terminal and its j a hooked tail, which read as fussy in names and
// headlines.
// Atkinson Hyperlegible for body, drawn by the Braille Institute for
// legibility, which suits an audience that includes grandparents. Two other
// faces were tried in between; the letterform Benny disliked turned out to be
// in the display face, not this one.
const HREF =
  "https://fonts.googleapis.com/css2" +
  "?family=Lora:wght@400;600;700" +
  "&family=Atkinson+Hyperlegible:wght@400;700" +
  "&display=swap";

const css = await (await fetch(HREF, { headers: { "User-Agent": UA } })).text();

fs.mkdirSync(OUT, { recursive: true });

// Keep latin and latin-ext only. The school is in New York.
const blocks = css.split("/*").filter((b) => /^\s*(latin|latin-ext)\s*\*\//.test(b));

// Google serves the same variable font file for every requested weight of a
// variable family, so dedupe by content hash and collapse those weights into
// a single rule with a weight range.
const byHash = new Map();
const faces = [];

for (const block of blocks) {
  const url = block.match(/src:\s*url\(([^)]+)\)/)?.[1];
  const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
  const weight = block.match(/font-weight:\s*([^;]+);/)?.[1].trim();
  const style = block.match(/font-style:\s*([^;]+);/)?.[1].trim();
  const range = block.match(/unicode-range:\s*([^;]+);/)?.[1].trim();
  if (!url || !family) continue;

  const subset = block.match(/^\s*(latin-ext|latin)\s*\*\//)[1];
  const buf = Buffer.from(await (await fetch(url)).arrayBuffer());
  const hash = createHash("sha256").update(buf).digest("hex").slice(0, 8);

  let file = byHash.get(hash);
  if (!file) {
    const slug = family.toLowerCase().replace(/\s+/g, "-");
    file = `${slug}-${subset}-${hash}.woff2`;
    fs.writeFileSync(path.join(OUT, file), buf);
    byHash.set(hash, file);
  }

  const existing = faces.find((f) => f.file === file && f.style === style);
  if (existing) {
    existing.weights.add(Number(weight));
  } else {
    faces.push({ family, style, range, file, weights: new Set([Number(weight)]) });
  }
}

let sheet = "/* Generated by tools/fetch-fonts.mjs. Do not edit by hand. */\n";
for (const face of faces) {
  const w = [...face.weights].sort((a, b) => a - b);
  const weight = w.length > 1 ? `${w[0]} ${w[w.length - 1]}` : `${w[0]}`;
  sheet +=
    `\n@font-face {\n` +
    `  font-family: '${face.family}';\n` +
    `  font-style: ${face.style};\n` +
    `  font-weight: ${weight};\n` +
    `  font-display: swap;\n` +
    `  src: url('/fonts/${face.file}') format('woff2');\n` +
    `  unicode-range: ${face.range};\n}\n`;
}

fs.writeFileSync(CSS, sheet);

const bytes = [...byHash.values()].reduce((n, f) => n + fs.statSync(path.join(OUT, f)).size, 0);
console.log(`${byHash.size} font files, ${(bytes / 1024).toFixed(0)} KB total`);
console.log(`${faces.length} @font-face rules`);
console.log(`wrote ${path.relative(ROOT, CSS)}`);
